[package]
name = "glkterm-rs"
version = "0.1.0"
links = "ncurses"
build = "build.rs"

[dependencies]
glk-rs = { path = "../glk", version = "0.1" }

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3"

[lib]
name = "glkterm"
